fileob = open('read.txt')
print(fileob.tell())
print(fileob.read())
print(fileob.tell())
print(fileob.readable())
print(fileob.readline())
fileob.seek(0)
print(fileob.readlines())
print(fileob.tell())
fileob.close()
